### ISSUE TITLE
There are not .atlas files in images/ folder

### ISSUE THREAD

**Issue by QuangNhat** [MapleScotDevelopment/LoggerBill#3]
Hi,
I am a new dev with Libgdx, I have just import your project and when I run it, I realize in folder images/ (internal) there are not .atlas files. There are only .png files there.
Can you update it with .atlas files or send for me ? (my mail: doquangnhat1@gmail.com )
Thank you for sharing and helping.

**Comment by duriej** [comment]
Hi,

Sorry about them they must have gotten removed with the addition of FireOS support.
They are back now.
